// Bundles the native facade for JavaScriptCore and copies the shims next to
// it. The output is committed (the iOS build must not need Node), and CI
// rebuilds it and fails on any difference, so it never drifts from source.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "rolldown";

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(here, "..");
const outDir = resolve(
  packageRoot,
  "../../apps/ios/Packages/SuperGongikKit/Sources/SGCore/Resources",
);
mkdirSync(outDir, { recursive: true });

const outFile = resolve(outDir, "sg-core.js");
await build({
  input: resolve(packageRoot, "src/entry-ios.ts"),
  platform: "neutral",
  resolve: { alias: { "@": resolve(packageRoot, "../../apps/web/src") } },
  logLevel: "warn",
  output: {
    file: outFile,
    format: "iife",
    minify: false,
    sourcemap: false,
    banner:
      "/* GENERATED by packages/native-core/scripts/build-ios.mjs. Do not edit. */",
  },
});

// Strip trailing whitespace differences so the committed file is stable.
writeFileSync(outFile, readFileSync(outFile, "utf8").replace(/[ \t]+$/gm, ""));
copyFileSync(
  resolve(packageRoot, "shims/jsc-shims.js"),
  resolve(outDir, "sg-shims.js"),
);
console.log(`wrote ${outFile}`);
